# Generated by Django 3.0.4 on 2020-03-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NuUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('marital_status', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('social_class', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('dependents', models.IntegerField(default=0)),
                ('region', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('food_expense', models.FloatField(default=0)),
                ('services_expense', models.FloatField(default=0)),
                ('education_expense', models.FloatField(default=0)),
                ('restaurants_expense', models.FloatField(default=0)),
                ('house_expense', models.FloatField(default=0)),
                ('debts_expense', models.FloatField(default=0)),
                ('investiments_expense', models.FloatField(default=0)),
                ('recreation_expense', models.FloatField(default=0)),
                ('health_expense', models.FloatField(default=0)),
                ('transport_expense', models.FloatField(default=0)),
                ('beauty_expense', models.FloatField(default=0)),
                ('others_expense', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('nuuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.NuUser')),
            ],
            bases=('users.nuuser',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Profile')),
            ],
            bases=('users.profile',),
        ),
    ]
