# Generated by Django 3.0.4 on 2020-03-12 02:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsNuUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_filters', jsonfield.fields.JSONField()),
            ],
        ),
    ]
