# Generated by Django 3.0.4 on 2020-03-12 02:12

from django.db import migrations
import json
from data.data_API import DataAPI

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'StatisticsNuUser')
    db_alias = schema_editor.connection.alias

    filter_list = ['Alimentacao', 'Assinatura_e_servico', 'Educacao',
                   'Beleza', 'Saude', 'Transporte', 'Outros', 'Saques']

    dat = DataAPI()
    for i in range(100):
        print(i)
        user_data = {}
        for fil in filter_list:
            user_data[fil] = dat.readInstructions(json.dumps({
                    "ID": i+1,
                    "feature": 'statistics',
                    "filter": fil
                }))
        user = User(user_filters = user_data)

        user.save()
       
        

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_statisticsnuuser'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]

