# Generated by Django 3.0.4 on 2020-03-12 22:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPGNuUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_summary', jsonfield.fields.JSONField()),
            ],
        ),
    ]
